# Generated by Django 4.1.5 on 2023-01-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_screens', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ohlcv',
        ),
        migrations.DeleteModel(
            name='OhlcvDummy',
        ),
    ]
